### ISSUE TITLE
Postman fails to import collection

### ISSUE THREAD

**Issue by mpitts** [npearce/F5_iWorkflow_REST_API_Commands#1]
When using the "Import From Link" for the link "https://github.com/npearce/F5_iWorkflow_iControl.REST_API_Commands/blob/master/iWorkflow%20Lab.postman_environment.json" Postman throws the error: "Failed to import data: format not recognized".

![error](https://cloud.githubusercontent.com/assets/17790238/19079487/650c4e14-8a19-11e6-9570-06fc29ab5c64.png)

Postman version is 4.7.2 on win / x86-32, Chrome 53.0.2785.116

**Comment by npearce** [comment]
Hi Matt, try grabbing the 'Raw' link.

There's a button in the top right corner labelled "raw" which gives you the JSON formatted file without any extra formatting. Here's the URL I just grabbed just now:

[https://raw.githubusercontent.com/npearce/F5_iWorkflow_REST_API_Commands/master/iWorkflow%20Lab.postman_environment.json](https://raw.githubusercontent.com/npearce/F5_iWorkflow_REST_API_Commands/master/iWorkflow%20Lab.postman_environment.json)

Regards,
Nathan

**Comment by mpitts** [comment]
Perfect, that works. Thanks for the quick reply.

**Comment by npearce** [comment]
I've changed the README.md to show the 'raw' links for the POSTMAN collections to ease POSTMAN importing.
